version: "3"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=ap-northeast-1
    volumes:
      - ./init-aws:/docker-entrypoint-initaws.d
